### ISSUE TITLE
Recursive toJSON function.

### ISSUE THREAD

**Issue by tom-drake** [pstadler/dtox#6]
Hi,

I've been using this library for a while and think its great for mapping my API calls onto a well defined structure. It would be great if I could call toJSON() on a top level DTO and get the full object back as translated. Is this something planned for?

I can open a pull request with an additional method if this sounds of interest?

Thanks

**Comment by pstadler** [comment]
Glad to hear that.

`toJSON` is a function with special behavior reserved for `JSON.stringify()`. See here: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#toJSON()_behavior

I'm not sure if this would break things. Any thoughts on this @mweibel?

**Comment by tom-drake** [comment]
@pstadler Currently using JSON.parse(JSON.stringify(DTOObject)) works fine. Is this the intended use if I would like to use my data as an object?

**Comment by mweibel** [comment]
`toJSON()` methods are getting called when calling `JSON.stringify()` on any instances of a class which implements such a method. 
dtox has such methods defined for all classes and therefore calling the stringify function will correctly translate back only the parsed data within the dtox objects.
Calling `JSON.parse(JSON.stringify(DTOObject))` can be seen as: copy all data from `DTOObject` into a new object completely unrelated to dtox. 
Example: https://github.com/pstadler/dtox/blob/master/examples/index.js

On line 66: `console.log(JSON.stringify(users)); // will print the items in JSON form`
Outputs:
```
[{"id":123,"name":"john_doe","roles":["owner"],"validated":true,"dateCreated":"1997-07-16T19:20:30.000Z"},{"id":124,"name":"jane_doe","roles":["administrator"],"validated":false,"dateCreated":"2015-12-15T07:36:25.000Z"}]
```

If you do:
`console.log(JSON.parse(JSON.stringify(users)));`
Output:
```
[ { id: 123,
    name: 'john_doe',
    roles: [ 'owner' ],
    validated: true,
    dateCreated: '1997-07-16T19:20:30.000Z' },
  { id: 124,
    name: 'jane_doe',
    roles: [ 'administrator' ],
    validated: false,
    dateCreated: '2015-12-15T07:36:25.000Z' } ]
```
It's formatted differently because the second log prints the JS objects and not the string.
This you can see if you do the following:
```
console.log(typeof JSON.stringify(users)); // string
console.log(typeof JSON.parse(JSON.stringify(users))); // object
```
Is this explanation making things clearer?

I'm interested in knowing why you're doing that? :)

**Comment by tom-drake** [comment]
I'm using dtox (possibly incorrectly) as a sanitation method on APIs which return JSON. In my project I have several DTOs and another which uses them as values.

```
const DATA_MAPPING = {
  dtoA: fields.objectWithDTO(DTOA),
  dtoB: fields.objectWithDTO(DTOB),
  dtoC: fields.listWithDTO(DTOC)
};
```
However this gives me a top level DTO with classes as values. I was using the `JSON.parse(JSON.stringify(DTOObject))` to remove the class entries such as `dtoObject.dtoA.value...` and rebuild the object how my app would expect it.

**Comment by mweibel** [comment]
That's a completely valid usecase and actually why we've built dtox in the first place (for our API clients to return a consistent value which we know is correct). 
Still curious why you want to remove the class entries though? Most of the operations you can do on a normal object/array should be doable directly on a dtox class instance as well.

**Comment by tom-drake** [comment]
Yep that seems to work as you expected without the `JSON.parse(JSON.stringify(DTOObject))`. Apologies for the error on my part.

**Comment by mweibel** [comment]
No worries :) Great it works out!

**Comment by tom-drake** [comment]
Thanks a lot for the help :)
